language: ruby

install:
  # Install Jekyll and dependencies
  - bundle install

script: bundle exec rake site:deploy --quiet

env:
  global:
    secure: "hKXULzhhJ69pd90hrONHHYYnH0VWAAd4bguBsZGqZ+UB1cvhM98gaoRC2uQ/ouocj8w3wbxtLKSF2PZS4AaTzic7ylRBIZqLFvogGYhUMH6iederbeoChJw/YjmZfFHJHwH+G0SfRnjtxJYH70+ZMERnSMB3SQQrjS2XnCky7uI="
