name: Google Cloud Documentation
markdown: kramdown
kramdown:
  input: GFM
  html_to_native: true
  hard_wrap: false
  use_coderay: true
baseurl: /
safe: false
lsi: false
pygments: true

relative_source: ../googledevdocs.github.io/
destination: ./googledevdocs.github.io/_site/

username: GoogleDevDocs
repo: googledevdocs.github.io
branch: master

permalink: pretty

paginate: 10
paginate_path: "blog/page:num"

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
